import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./ui/navigation/page";
import Footer from "./ui/footer/page";

export const metadata: Metadata = {
  title: "CarterDesigner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
