import type { Metadata } from "next";
import Navigation from "../ui/navigation/page";

export const metadata: Metadata = {
  title: "About - CarterDesigner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
