import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./ui/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-screen min-h-screen overflow-hidden overflow-y-scroll">
      <body className="w-full h-full">
        <Navigation />
        {children}
      </body>
    </html>
  );
}
